name: Expire Jobs
on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Expire Jobs
        run: |
          curl --request GET \
          --url 'https://mycareerlist.com/api/expire'
