name: Weekly newsletter
on:
  schedule:
    - cron: '0 0 * * 0'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Weekly newsletter
        run: |
          curl --request GET \
          --url 'https://mycareerlist.com/api/newsletter'
